var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/apps/[slug]/privacy/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_h.4ul._.js")
R.c("server/chunks/ssr/src_lib_apps_ts_05pfi7s._.js")
R.c("server/chunks/ssr/node_modules_0chu_mr._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_083u9v~.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~rwuo.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p3qowm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06u0kr8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0cgjcta._.js")
R.c("server/chunks/ssr/src_11clu~4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_apps_[slug]_privacy_page_actions_0~rpm0j.js")
R.m(83850)
module.exports=R.m(83850).exports
