var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/about/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qqvo7o._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_12z_yvf.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~rwuo.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p3qowm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_06u0kr8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0cgjcta._.js")
R.c("server/chunks/ssr/src_11clu~4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_about_page_actions_0j9pj4n.js")
R.m(52389)
module.exports=R.m(52389).exports
